/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoinf156;

/**
 *
 * @author Administrador
 */
public class About extends javax.swing.JInternalFrame {

    /**
     * Creates new form About
     */
    public About() {
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

	jPanel1 = new javax.swing.JPanel();
	jLabel1 = new javax.swing.JLabel();
	jLabel2 = new javax.swing.JLabel();
	jLabel3 = new javax.swing.JLabel();
	jLabel4 = new javax.swing.JLabel();
	jLabel5 = new javax.swing.JLabel();
	jLabel6 = new javax.swing.JLabel();
	jLabel7 = new javax.swing.JLabel();
	jLabel8 = new javax.swing.JLabel();
	jLabel9 = new javax.swing.JLabel();
	jLabel10 = new javax.swing.JLabel();

	setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

	jPanel1.setBackground(new java.awt.Color(0, 0, 0));

	jLabel1.setBackground(new java.awt.Color(102, 102, 102));
	jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
	jLabel1.setForeground(new java.awt.Color(255, 255, 255));
	jLabel1.setText("Metodos Directos Para Resolver");

	jLabel2.setForeground(new java.awt.Color(204, 204, 204));
	jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/eins.jpg"))); // NOI18N
	jLabel2.setText(" ");

	jLabel3.setForeground(new java.awt.Color(255, 255, 255));
	jLabel3.setText("Ruddy Condori Topoco");

	jLabel4.setForeground(new java.awt.Color(204, 204, 204));
	jLabel4.setText("_");

	jLabel5.setForeground(new java.awt.Color(204, 204, 204));
	jLabel5.setText("__");

	jLabel6.setForeground(new java.awt.Color(204, 204, 204));
	jLabel6.setText("___");

	jLabel7.setForeground(new java.awt.Color(204, 204, 204));
	jLabel7.setText("____");

	jLabel8.setForeground(new java.awt.Color(204, 204, 204));
	jLabel8.setText("_____");

	jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
	jLabel9.setForeground(new java.awt.Color(255, 255, 255));
	jLabel9.setText("Sistemas de Ecuaciones Lineales");

	jLabel10.setForeground(new java.awt.Color(255, 255, 255));
	jLabel10.setText("rucocool@hotmail.com");

	javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
	jPanel1.setLayout(jPanel1Layout);
	jPanel1Layout.setHorizontalGroup(
	    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	    .addGroup(jPanel1Layout.createSequentialGroup()
		.addGap(26, 26, 26)
		.addComponent(jLabel2)
		.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		    .addGroup(jPanel1Layout.createSequentialGroup()
			.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
			.addComponent(jLabel9))
		    .addGroup(jPanel1Layout.createSequentialGroup()
			.addGap(27, 27, 27)
			.addComponent(jLabel1))
		    .addGroup(jPanel1Layout.createSequentialGroup()
			.addGap(33, 33, 33)
			.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			    .addComponent(jLabel7)
			    .addComponent(jLabel8)
			    .addComponent(jLabel6)
			    .addComponent(jLabel5)
			    .addComponent(jLabel3)
			    .addComponent(jLabel4)
			    .addGroup(jPanel1Layout.createSequentialGroup()
				.addGap(32, 32, 32)
				.addComponent(jLabel10)))))
		.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	);
	jPanel1Layout.setVerticalGroup(
	    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	    .addGroup(jPanel1Layout.createSequentialGroup()
		.addGap(31, 31, 31)
		.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
		    .addGroup(jPanel1Layout.createSequentialGroup()
			.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
			.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
			.addComponent(jLabel9)
			.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
			.addComponent(jLabel3)
			.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
			.addComponent(jLabel4)
			.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
			.addComponent(jLabel5)
			.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
			.addComponent(jLabel6)
			.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
			.addComponent(jLabel7)
			.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
			.addComponent(jLabel8)
			.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
			.addComponent(jLabel10))
		    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
		.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	);

	javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	getContentPane().setLayout(layout);
	layout.setHorizontalGroup(
	    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	);
	layout.setVerticalGroup(
	    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	);

	pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
