/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoinf156;

import java.awt.GridLayout;

/**
 *
 * @author RuCo
 */
public class FrameDoolite extends javax.swing.JInternalFrame {
    /** Creates new form EliminacionGaussiana */
    private String etapas;
    double[][] matriz;
    int filas;
    int columnas;
    String proceso = "";

    /**
     * Creates new form FrameDoolite
     */
    public FrameDoolite(double[][] matriz, int filas, int columnas) {
        initComponents();
        this.matriz = matriz;
        this.filas = filas;
        this.columnas = columnas;
        calcularDoolittle(matriz);
    }
    private FrameDoolite() {
        throw new UnsupportedOperationException("Not yet implemented");
    }
    
    public void calcularDoolittle(double[][] matriz) {
        int n = matriz.length;
        
        double[] resultadoz = new double[n];
        double[] resultadox = new double[n];
        double[][] matrizl = new double[n][n];
        double[][] matrizu = new double[n][n];
        
        for (int i = 0; i < n; ++i) {
            matrizl[i][i] = 1.0D;
        }
        for (int i = 0; i < n; ++i) {
            for (int j = 0; j < n; ++j) {
                double suma = 0.0D;
                for (int k = 0; k < n; ++k) {
                    suma += matrizl[i][k] * matrizu[k][j];
                }
                if (j >= i)
                    matrizu[i][j] = (matriz[i][j] - suma);
                else {
                    matrizl[i][j] = ((matriz[i][j] - suma) / matrizu[j][j]);
                }
            }
            PanelEtapasLU panelEtapas = new PanelEtapasLU();
            panelEtapas.setEtapa("Etapa " + (i + 1));
            panelEtapas.setModeloL(matrizl, filas, columnas - 1);
            panelEtapas.setModeloU(matrizu, filas, columnas - 1);
            panel.setLayout(new GridLayout(i + 1, 1));
            panel.add(panelEtapas);
            setSize(getWidth(), getHeight() + 1);
            setSize(getWidth(), getHeight() - 1);
        }
        for (int i = 0; i < n; ++i) {
            double suma = 0.0D;
            for (int j = i - 1; j >= 0; --j) {
                suma += matrizl[i][j] * resultadoz[j];
            }
            resultadoz[i] = ((matriz[i][n] - suma) / matrizl[i][i]);
        }
        String resultados = "";
        for (int i = 0; i < n; ++i) {
            resultados = (resultados + "Z" + (i + 1) + "= " + resultadoz[i] + "\n");
        }
        for (int i = n - 1; i >= 0; --i) {
            double suma = 0.0D;
            for (int j = i + 1; j < n; ++j) {
                suma += matrizu[i][j] * resultadox[j];
            }
            resultadox[i] = ((resultadoz[i] - suma) / matrizu[i][i]);
        }
        for (int i = 0; i < n; ++i) {
            resultados = (resultados + "X" + (i + 1) + "= " + resultadox[i] + "\n");
        }
        panelSoluciones panelSln = new panelSoluciones();
        panelSln.setSoluciones(resultados);
        panel.setLayout(new GridLayout(n+1, 1));
        panel.add(panelSln);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panel = new javax.swing.JPanel();

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(23, 23));
        jScrollPane1.setName("jScrollPanel1");
        jScrollPane1.setPreferredSize(new java.awt.Dimension(584, 525));

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setName("panel");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 523, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
