/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoinf156;

import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RuCo
 */
public class PanelSolCramer extends javax.swing.JPanel {
    DecimalFormat formateador;

    /**
     * Creates new form PanelSolCramer
     */
    public PanelSolCramer() {
        initComponents();
    }
    
    public void setEtapa(String etapa) {
        lbl_etapa.setText(etapa);
        DecimalFormatSymbols simbolos = new DecimalFormatSymbols();
        simbolos.setDecimalSeparator('.');
        formateador = new DecimalFormat("0.00E00");
    }
    
    public void setModelo(double matriz[][], int filas, int columnas) {
        DefaultTableModel modelo = new DefaultTableModel();
        for (int i = 0; i < columnas; i++) {
            modelo.addColumn("");
        }
        tablaL.setModel(modelo);
        for (int i = 0; i < filas; i++) {
            Vector fila = new Vector();
            for (int j = 0; j < columnas; j++) {
                fila.add(formateador.format(matriz[i][j]));
            }
            modelo.addRow(fila);
        }
        tablaL.setModel(modelo);
    }
    
    public void setDet(String det) {
        lbl_det.setText(det);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaL = new javax.swing.JTable();
        lbl_etapa = new javax.swing.JLabel();
        lbl_det = new javax.swing.JLabel();

        tablaL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "X1", "X2", "X3", "X4"
            }
        ));
        jScrollPane1.setViewportView(tablaL);

        lbl_etapa.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lbl_etapa.setText("ETAPA X");

        lbl_det.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lbl_det.setForeground(new java.awt.Color(0, 102, 153));
        lbl_det.setText("Det() = ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_etapa, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lbl_det, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbl_etapa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_det)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_det;
    private javax.swing.JLabel lbl_etapa;
    private javax.swing.JTable tablaL;
    // End of variables declaration//GEN-END:variables
}
