/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelEtapas.java
 *
 * Created on 12/10/2011, 03:25:30 PM
 */
package proyectoinf156;

import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author john
 */
public class PanelEtapasLU extends javax.swing.JPanel {

    DecimalFormat formateador;

    /** Creates new form PanelEtapas */
    public PanelEtapasLU() {
        initComponents();
    }

    public void setEtapa(String etapa) {
        lbl_etapa.setText(etapa);
        DecimalFormatSymbols simbolos = new DecimalFormatSymbols();
        simbolos.setDecimalSeparator('.');
        formateador = new DecimalFormat("0.00E00");
    }

    public void setModeloL(double matriz[][], int filas, int columnas) {
        DefaultTableModel modelo = new DefaultTableModel();
        for (int i = 0; i < columnas; i++) {
            modelo.addColumn("");
        }
        tablaL.setModel(modelo);
        for (int i = 0; i < filas; i++) {
            Vector fila = new Vector();
            for (int j = 0; j < columnas; j++) {
                fila.add(formateador.format(matriz[i][j]));
            }
            modelo.addRow(fila);
        }
        tablaL.setModel(modelo);
    }

    public void setModeloU(double matriz[][], int filas, int columnas) {
        DefaultTableModel modelo = new DefaultTableModel();
        for (int i = 0; i < columnas; i++) {
            modelo.addColumn("");
        }
        tablaU.setModel(modelo);
        for (int i = 0; i < filas; i++) {
            
            Vector fila = new Vector();
            for (int j = 0; j < columnas; j++) {
                fila.add(formateador.format(matriz[i][j]));
            }
            modelo.addRow(fila);
        }
        tablaU.setModel(modelo);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_etapa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaL = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaU = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_etapa.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lbl_etapa.setText("ETAPA X");
        lbl_etapa.setName("lbl_etapa"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tablaL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "X1", "X2", "X3", "X4"
            }
        ));
        tablaL.setName("tablaL"); // NOI18N
        jScrollPane1.setViewportView(tablaL);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        tablaU.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "X1", "X2", "X3", "X4"
            }
        ));
        tablaU.setName("tablaU"); // NOI18N
        jScrollPane2.setViewportView(tablaU);

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel1.setText("MATRIZ L");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel2.setText("MATRIZ U");
        jLabel2.setName("jLabel2"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lbl_etapa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_etapa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_etapa;
    private javax.swing.JTable tablaL;
    private javax.swing.JTable tablaU;
    // End of variables declaration//GEN-END:variables
}
