/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * pnlVariables.java
 *
 * Created on 26/10/2011, 06:07:22 PM
 */
package proyectoinf156;

import javax.swing.JTextField;

/**
 *
 * @author john
 */
public class pnlVariables extends javax.swing.JPanel {

    /** Creates new form pnlVariables */
    String nombreVariable;
    public pnlVariables(String nombreVariable) {
        initComponents();
        this.nombreVariable = nombreVariable;
        lblX.setText(nombreVariable);
    }
    
    JTextField getTxt(){
        return txtX;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblX = new javax.swing.JLabel();
        txtX = new javax.swing.JTextField();

        lblX.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblX.setText("XN:");
        lblX.setName("lblX"); // NOI18N

        txtX.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        txtX.setName("txtX"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtX, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblX)
                .addComponent(txtX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblX;
    private javax.swing.JTextField txtX;
    // End of variables declaration//GEN-END:variables
}
